version: '3'

services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: go-chatgpt-api:1.0
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped
    network_mode: "host"
