version: '3'

services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: go-chatgpt-api:1.0
    ports:
      - "4141:4141"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=
      - GO_CHATGPT_API_PORT=4141
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=https://arkose-token.linweiyuan.com
    restart: unless-stopped
    network_mode: "host"
