version: '3'

services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: go-chatgpt-api
    ports:
      - 8180:8180
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped
